server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name myhiphopblog.chkontog.com;

    client_max_body_size 510m;

    location / {
        proxy_pass http://127.0.0.1:3020;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 600s;
        proxy_send_timeout 600s;
    }

    ssl_certificate /etc/letsencrypt/live/myhiphopblog.chkontog.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/myhiphopblog.chkontog.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    listen 80;
    listen [::]:80;
    server_name myhiphopblog.chkontog.com;
    return 301 https://myhiphopblog.chkontog.com$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name myhiphopblog.ypotitloi.gr;

    root /var/www/myhiphopblog-moved;

    location / {
        try_files /moved.html =404;
    }

    ssl_certificate /etc/letsencrypt/live/myhiphopblog.ypotitloi.gr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/myhiphopblog.ypotitloi.gr/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    listen 80;
    listen [::]:80;
    server_name myhiphopblog.ypotitloi.gr;
    return 301 https://myhiphopblog.ypotitloi.gr$request_uri;
}
